services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ~/homeassistant:/config
    network_mode: host

  esphome:
    image: ghcr.io/esphome/esphome
    container_name: esphome
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - ~/esphome:/config
      
  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper
    command: --model tiny-int8 --language en
    ports:
      - "10300:10300"
    restart: unless-stopped

  piper:
    container_name: piper
    image: rhasspy/wyoming-piper
    command: --voice en_US-lessac-medium
    ports:
      - "10200:10200"
    restart: unless-stopped

  openwakeword:
    container_name: openwakeword
    image: rhasspy/wyoming-openwakeword
    ports:
      - "10400:10400"
    restart: unless-stopped

  esp32-backend:
    build:
      context: ./backend  # Đường dẫn tới thư mục chứa Dockerfile
      dockerfile: Dockerfile
    container_name: esp32_backend
    restart: always
    ports:
      - "6060:6000"
      - "10500:10500"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    env_file:
      - ./backend/.env
